# Generated by Django 4.2.25 on 2026-04-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingplan',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
