# Generated by Django 4.2.25 on 2026-04-28 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memberships', '0002_membershipplan_billing_cycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='coach_notes',
            field=models.TextField(blank=True, help_text='Important notes from the coach'),
        ),
        migrations.AddField(
            model_name='membership',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='membership',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('expired', 'Expired'), ('canceled', 'Canceled'), ('postponed', 'Postponed')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='MembershipNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='memberships.membership')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
