# Generated by Django 4.2.25 on 2026-04-28 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0003_membership_coach_notes_membership_duration_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='postponed_remaining_days',
            field=models.PositiveIntegerField(blank=True, help_text='Days remaining when the membership was postponed. Used to restore the countdown on re-activation.', null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='coach_notes',
            field=models.TextField(blank=True, help_text='Permanent instructions from the coach — always visible to the trainee.'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60, help_text='Session length in minutes.'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, help_text='The daily session start time (date portion is ignored; only time matters).', null=True),
        ),
    ]
