# Generated by Django 4.2.25 on 2026-05-13 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0004_add_postponed_remaining_days'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membershipnote',
            options={'ordering': ['-is_pinned', 'created_at']},
        ),
        migrations.AddField(
            model_name='membershipnote',
            name='is_pinned',
            field=models.BooleanField(default=False, help_text='Pinned notes always appear at the top of the chat thread.'),
        ),
    ]
