# Generated by Django 4.2.25 on 2026-05-13 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0005_add_note_pinned_resume'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membershipnote',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveField(
            model_name='membershipnote',
            name='is_pinned',
        ),
    ]
